### ISSUE TITLE
[BUG] souvenir recherche de samahdi

### ISSUE THREAD

**Issue by schynriu** [faresBelmadi/GF#48]
**Describe the bug**
J'ai pris le souvenir recherche de samahdi
Et j'ai ensuite pris une capa amasser les richesses a l'autel
Sauf qu'au combat ,je me retrouve avec deux versions de roi sans couronne, une version nornale et une version souvenir

Supposition, la capa spéciale a "écraser" la mauvaise capa et je me retrouve avec un doublon

** Scene**
Combat

**Expected behavior**
Avoir la capa spécial roi sans couronne, et la capa amasser les richesses normale

**Current behavior**
A sentence to describe what is happening on your screen
**To Reproduce**
Acheter la capa roi sans couronne
Prendre un souvenir recherche de samahdi
acheter ensuite la capa amasser les richesses
allez au combat suivant

**Spells and memories unlocked**
Recherche de samahdi
roi sans couronne
amasser les richesses 

**Screenshots**
![image](https://github.com/user-attachments/assets/de5d27c4-8411-4e8c-8e46-f7edd4993a7c)

**Comment by NicolasValette** [comment]
Fix in 0.2.1.3
