### ISSUE TITLE
[BUG] Sélection de sort et changement de sorts

### ISSUE THREAD

**Issue by xSternLeVegetal** [faresBelmadi/GF#6]
**Describe the bug**
si on clique sur un sors, puis sur un autre , le premier ce lance immédiatement

** Scene**
combat

**Expected behavior**
pouvoir changer de sors sans que le premier ne ce lance

**Current behavior**
si on clique sur un sors, puis sur un autre , le premier ce lance immédiatement

**To Reproduce**
1-combat 
2-sélectionner un sors
3-sélectiponner un autre sors

**Spells and memories unlocked**
premier combat : sors de base

**Screenshots**

**Additional context**

**Comment by kohotatsu** [comment]
Impossible à reproduire, probablement déjà réglé.
