### ISSUE TITLE
More indication at level selection

### ISSUE THREAD

**Issue by Elayan** [faresBelmadi/GF#61]
**Is your feature request related to a problem? Please describe.**
Took me a while to realize it wasn't a (non-animated) waiting screen. Even when I moved my mouse, I didn't notice right away that the tree was responsive: the slight hue change is barely visible to me.

**Describe the solution you'd like**
Something clearly noticeable when hovering the level, a big ornated animated circle around the tree would be amazing without needing to alter the cute tree art.
Maybe an info somewhere to say this page is a level selector?

**Additional context**
![20241017180534_1](https://github.com/user-attachments/assets/6fc43694-ab83-4c17-8067-f80cc6d523bc)

**Comment by faresBelmadi** [comment]
this level selection screen will be removed in the next tutorial patch so i'm closing this issue
