### ISSUE TITLE
Why the map change?

### ISSUE THREAD

**Issue by Elayan** [faresBelmadi/GF#67]
**Is your feature request related to a problem? Please describe.**
I first thought the "circle" map was the entire tutorial, but actually everything was super packed in one single fight. But then the map... changed? Why?

**Describe the solution you'd like**
Keep one map, call the level "Tutorial", make it simple to understand.
When we see the map the first two times during tutorial, maybe the next level could be hidden? (in a fog?)

**Additional context**
![20241017180534_1](https://github.com/user-attachments/assets/d0fd3c29-6336-43e8-88fd-7695a6810edd)
![20241018170906_1](https://github.com/user-attachments/assets/81548942-820e-4dd1-aa2a-bddb9040b18f)

**Comment by faresBelmadi** [comment]
the first map is from an old version of the tutorial that wasn't removed yet, it will be removed soon with the second map being the only one
