### ISSUE TITLE
[BUG] Language selection fr not working

### ISSUE THREAD

**Issue by faresBelmadi** [faresBelmadi/GF#75]
**Describe the bug**
Can't change language to french

** Scene**
Main menu

**Expected behavior**
change the game language to french

**Current behavior**
clicking on the french language doesn't switch

**To Reproduce**
1. Click on option
2. click on  the french flag
3. language is still english

**Spells and memories unlocked**
If the bug is linked to the battle scene, please include the unlocked spells and equiped memories

**Screenshots**

**Additional context**

**Comment by NicolasValette** [comment]
Fixed #87
